import {
  Award,
  Boxes,
  Carrot,
  Coins,
  Compass,
  Fish,
  Gift,
  LayoutGrid,
  Megaphone,
  Package,
  Palmtree,
  PawPrint,
  MessageSquare,
  Puzzle,
  ScrollText,
  Skull,
  Sparkles,
  Store,
  Trophy,
  Tv,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Ta sama ikona per plugin co w PluginGraph.tsx (ekosystem na Dashboardzie) - osobna
// kopia mapy zamiast importu stamtąd, żeby nie ryzykować refaktoru już przetestowanego
// komponentu. Używane jako ikona nagłówka na PluginDetailPage.tsx.
export const PLUGIN_ICONS: Record<string, LucideIcon> = {
  core: Puzzle,
  advancements: Trophy,
  chatfilter: MessageSquare,
  crates: Gift,
  dungeons: Skull,
  fishing: Fish,
  generators: Boxes,
  hud: Tv,
  market: Coins,
  quests: ScrollText,
  ranks: Award,
  redstone: Zap,
  shop: Store,
  skyblock: Palmtree,
  spawn: Compass,
  spawners: PawPrint,
  tools: Wrench,
  announcer: Megaphone,
  farming: Carrot,
  menu: LayoutGrid,
  teleport: Sparkles,
};

/** Domyślna ikona dla pakietów (nie są "pluginem" same w sobie, więc nie ma dla nich wpisu wyżej). */
export const PACKAGE_ICON: LucideIcon = Package;

/** Czytelna nazwa per id pluginu (te same id co PLUGIN_ICONS i embedded_jars.rs). */
export const PLUGIN_LABELS: Record<string, string> = {
  core: "Core (wspólne API + licencje)",
  advancements: "Osiągnięcia",
  chatfilter: "Filtr czatu",
  crates: "Skrzynki",
  dungeons: "Loch i boss",
  fishing: "Wędkarstwo",
  generators: "Generatory",
  hud: "HUD i placeholdery",
  market: "Rynek graczy",
  quests: "Questy",
  ranks: "Rangi",
  redstone: "Redstone-urządzenia",
  shop: "Sklep (ekonomia)",
  skyblock: "Skyblock",
  spawn: "Spawn, warpy, obszary",
  spawners: "Customowe spawnery",
  tools: "Custom itemy i narzędzia",
  announcer: "Announcer",
  farming: "Uprawy specjalne",
  menu: "Główne menu serwera",
  teleport: "Teleporty",
};
